"""Native uploads exercised only against the disposable smoke wiki."""

import http.cookiejar
import json
import secrets
import struct
import time
import urllib.error
import urllib.parse
import urllib.request
import zlib


def png(width=32, height=16, pixel=b"\x12\x34\x56", size=None):
    def chunk(kind, data):
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))

    body = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
    body += chunk(b"IDAT", zlib.compress((b"\0" + pixel * width) * height))
    if size is not None:
        body += chunk(b"npAd", b"x" * (size - len(body) - 24))
    return body + chunk(b"IEND", b"")


class UploadClient:
    def __init__(self, base):
        self.base = base
        self.opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(http.cookiejar.CookieJar()))
        self.token = "+\\"

    def request(self, parameters, file=None, file_field="file"):
        parameters = dict(format="json", **parameters)
        if file is None:
            request = urllib.request.Request(self.base + "/api.php", urllib.parse.urlencode(parameters).encode())
        else:
            boundary = "mirklurk-" + secrets.token_hex(16)
            parts = []
            for key, value in parameters.items():
                parts.append(f'--{boundary}\r\nContent-Disposition: form-data; name="{key}"\r\n\r\n{value}\r\n'.encode())
            parts.append(f'--{boundary}\r\nContent-Disposition: form-data; name="{file_field}"; filename="fixture.png"\r\n'
                         'Content-Type: application/octet-stream\r\n\r\n'.encode())
            parts.extend([file, f"\r\n--{boundary}--\r\n".encode()])
            request = urllib.request.Request(self.base + "/api.php", b"".join(parts),
                                             {"Content-Type": f"multipart/form-data; boundary={boundary}"})
        try:
            response = self.opener.open(request, timeout=90)
        except urllib.error.HTTPError as error:
            if error.code != 429:
                raise
            response = error
        with response:
            return json.load(response)

    def login(self, name, password):
        token = self.request({"action": "query", "meta": "tokens", "type": "login"})["query"]["tokens"]["logintoken"]
        result = self.request({"action": "login", "lgname": name, "lgpassword": password, "lgtoken": token})
        if result.get("login", {}).get("result") != "Success":
            raise RuntimeError(f"Upload fixture login failed: {result}")
        self.token = self.request({"action": "query", "meta": "tokens"})["query"]["tokens"]["csrftoken"]

    def upload(self, name, content=None, **parameters):
        return self.request({
            "action": "upload", "filename": name, "token": self.token, "ignorewarnings": 1,
            "comment": "Original synthetic image generated by the disposable upload smoke; no game assets.",
            **parameters,
        }, content)


def success(result):
    if result.get("upload", {}).get("result") != "Success":
        raise RuntimeError(f"Native upload failed: {result}")
    return result["upload"]


def rejected(result, *codes):
    code = result.get("error", {}).get("code")
    if code not in codes:
        raise RuntimeError(f"Upload must fail with {codes}, got {result}")


def smoke_uploads(run, api, base, admin_password, editor_password):
    anonymous = UploadClient(base)
    rejected(anonymous.upload("Anonymous-denied.png", png()), "mustbeloggedin", "permissiondenied", "writeapidenied")
    editor = UploadClient(base)
    editor.login("TestEditor", editor_password)
    rejected(editor.upload("Newcomer-denied.png", png()), "permissiondenied")
    user_token = api({"action": "query", "meta": "tokens", "type": "userrights"})["query"]["tokens"]["userrightstoken"]
    api({"action": "userrights", "user": "TestEditor", "add": "confirmed",
         "reason": "Synthetic uploader confirmation", "token": user_token}, post=True)
    rights = editor.request({"action": "query", "meta": "userinfo", "uiprop": "rights|groups"})["query"]["userinfo"]
    if not {"upload", "reupload-own"} <= set(rights["rights"]) or {"sysop", "bureaucrat"} & set(rights["groups"]):
        raise RuntimeError("Manual confirmation did not enable uploads without administrator privileges.")
    if {"reupload", "reupload-shared", "noratelimit"} & set(rights["rights"]):
        raise RuntimeError("Ordinary uploaders inherited replacement or throttle bypass permissions.")
    with editor.opener.open(base + "/w/Special:Upload", timeout=30) as response:
        form = response.read().decode()
    if not all(text in form for text in ("wpUploadFile", "12 megapixels", "permission or", "20 upload attempts")):
        raise RuntimeError("Special:Upload is missing its native form or contribution instructions.")
    first = success(editor.upload("Contributor-diagram.png", png()))
    second = success(editor.upload("Contributor-diagram.png", png(pixel=b"\x34\x56\x78")))
    history = api({"action": "query", "titles": "File:Contributor-diagram.png",
                   "prop": "imageinfo", "iiprop": "user|url", "iilimit": 5})["query"]["pages"]
    revisions = next(iter(history.values()))["imageinfo"]
    if len(revisions) != 2 or any(row["user"] != "TestEditor" for row in revisions):
        raise RuntimeError("Own-file replacement must retain both revisions and attribution.")
    for upload in (first, second):
        with urllib.request.urlopen(upload["imageinfo"]["url"], timeout=30) as response:
            if response.headers.get_content_type() != "image/png":
                raise RuntimeError("Public uploads must remain anonymously readable as images.")
    page = next(iter(api({"action": "query", "titles": "File:Contributor-diagram.png", "prop": "imageinfo",
                          "iiprop": "url|size", "iiurlwidth": 16})["query"]["pages"].values()))
    thumbnail = page["imageinfo"][0]
    if (thumbnail.get("thumbwidth"), thumbnail.get("thumbheight")) != (16, 8):
        raise RuntimeError("A contributor's upload did not generate the expected thumbnail.")
    with urllib.request.urlopen(thumbnail["thumburl"], timeout=30) as response:
        if response.headers.get_content_type() != "image/png" or response.headers.get("X-Content-Type-Options") != "nosniff":
            raise RuntimeError("Upload thumbnail delivery is missing its image type or nosniff policy.")

    admin = UploadClient(base)
    admin.login("WikiAdmin", admin_password)
    success(admin.upload("Operator-artwork.png", png(pixel=b"\x78\x56\x34")))
    rejected(editor.upload("Operator-artwork.png", png()), "fileexists-forbidden", "fileexists-shared-forbidden")
    success(admin.upload("Contributor-diagram.png", png(pixel=b"\x22\x44\x66")))
    # Replacement must not allow a contributor to reclaim a file last uploaded by an admin.
    rejected(editor.upload("Contributor-diagram.png", png()), "fileexists-forbidden")
    rejected(admin.upload("Remote.png", url="https://example.invalid/fixture.png"), "copyuploaddisabled")
    for extension, content in [
        ("svg", b'<svg xmlns="http://www.w3.org/2000/svg" width="1" height="1"/>'),
        ("gif", png()), ("pdf", b"%PDF-1.4\n"), ("zip", b"PK\x03\x04"),
        ("php", b"<?php echo 'synthetic'; ?>"), ("png", b"not an image"),
        ("jpg", png()),
    ]:
        rejected(admin.upload("Invalid." + extension, content), "filetype-banned", "verification-error")
    for width, height in [(4001, 3000), (3000, 4001), (8193, 1), (1, 8193)]:
        result = admin.upload(f"Oversized-{width}-{height}.png", png(width, height), stash=1)
        rejected(result, "verification-error")
        if "12 megapixels" not in result["error"]["info"]:
            raise RuntimeError("Oversized stashes need the dimension-limit error, not an unrelated rejection.")
    for width, height in [(3840, 2160), (4000, 3000), (8192, 1), (1, 8192)]:
        success(admin.upload(f"Boundary-{width}-{height}.png", png(width, height)))
    for extension, mime in [("jpg", "image/jpeg"), ("webp", "image/webp")]:
        content = run("exec", "-T", "--user", "www-data", "mirklurk", "/usr/bin/convert",
                      "png:-", extension + ":-", input_bytes=png())
        result = success(admin.upload("Allowed." + extension, content))
        if result["imageinfo"]["mime"] != mime:
            raise RuntimeError("An allowed format was not stored with the correct MIME type.")
        oversized = run("exec", "-T", "--user", "www-data", "mirklurk", "/usr/bin/convert",
                        "-size", "8193x1", "xc:white", extension + ":-")
        rejected(admin.upload("Oversized." + extension, oversized), "verification-error")
    stash = success(admin.upload("Stashed.png", png(pixel=b"\x11\x22\x33"), stash=1))
    success(admin.upload("Stashed.png", filekey=stash["filekey"]))
    success(admin.upload("Exact-10-MiB.png", png(size=10 * 1024 * 1024)))
    oversized = admin.upload("Over-10-MiB.png", png(size=10 * 1024 * 1024 + 1))
    rejected(oversized, "badupload")
    if oversized["error"].get("size") != 10485760:
        raise RuntimeError("PHP must reject uploads above exactly 10 MiB.")
    # Declared assembled size cannot bypass the cap through chunking.
    rejected(admin.request({"action": "upload", "filename": "Chunk-too-big.png", "token": admin.token,
                            "stash": 1, "filesize": 10485761, "offset": 0}, png(), file_field="chunk"),
             "file-too-large", "upload-error")

    # Native autoconfirmation requires BOTH thresholds. Alter only a disposable fixture account.
    run("exec", "-T", "mirklurk", "php", "maintenance/run.php", "createAndPromote",
        "AutoUploader", editor_password)
    for age, count, allowed in [(86300, 5, False), (86500, 4, False), (86500, 5, True)]:
        code = ("$db = MediaWiki\\MediaWikiServices::getInstance()->getConnectionProvider()->getPrimaryDatabase(); "
                f"$db->newUpdateQueryBuilder()->update('user')->set(['user_registration' => $db->timestamp(time()-{age}), "
                f"'user_editcount' => {count}])->where(['user_name' => 'AutoUploader'])->caller(__METHOD__)->execute(); "
                "MediaWiki\\User\\User::newFromName('AutoUploader')->invalidateCache();")
        run("exec", "-T", "mirklurk", "php", "maintenance/run.php", "eval", input_bytes=code.encode())
        auto = UploadClient(base)
        auto.login("AutoUploader", editor_password)
        actual = auto.request({"action": "query", "meta": "userinfo", "uiprop": "rights"})["query"]["userinfo"]["rights"]
        if ("upload" in actual) != allowed:
            raise RuntimeError(f"Autoconfirmation boundary failed: age={age}, edits={count}.")
    # Fresh eligible account: exactly 20 uploads, then a real native throttle error.
    for index in range(20):
        if index:
            time.sleep(7)  # Native uploads also count toward the existing ten-edits/minute limit.
        success(auto.upload(f"Rate-{index}.png", png(pixel=bytes((index, 21, 43)))))
    rejected(auto.upload("Rate-21.png", png()), "ratelimited")

    # The directory rules, not volume-provided .htaccess, must protect private bytes and scripts.
    code = ("foreach (['deleted', 'temp'] as $dir) { "
            "$path = '/var/www/html/images/' . $dir; if (!is_dir($path)) { mkdir($path, 0755, true); } "
            "file_put_contents($path . '/private.png', 'synthetic private bytes'); } "
            "file_put_contents('/var/www/html/images/probe.php', '<?php echo \"EXECUTED\";');")
    run("exec", "-T", "--user", "www-data", "mirklurk", "php", "-r", code)
    for path in ("/images/deleted/private.png", "/images/temp/private.png", "/images/probe.php", "/images/"):
        try:
            with urllib.request.urlopen(base + path, timeout=30) as response:
                raise RuntimeError(f"Private storage or script exposed over HTTP: {path}, {response.status}")
        except urllib.error.HTTPError as error:
            if error.code != 403:
                raise
    run("exec", "-T", "--user", "www-data", "mirklurk", "php", "-r",
        "foreach (['deleted/private.png', 'temp/private.png', 'probe.php'] as $p) { unlink('/var/www/html/images/' . $p); }")

    run("exec", "-T", "mirklurk", "php", "-r",
        "if (!is_dir('/var/lib/mirklurk-backup')) { mkdir('/var/lib/mirklurk-backup', 0755); } "
        "file_put_contents('/var/lib/mirklurk-backup/read-only', 'Synthetic coordinated backup');")
    try:
        locked = anonymous.request({"action": "query", "meta": "siteinfo", "siprop": "general"})["query"]["general"]
        if "readonly" not in locked or locked.get("readonlyreason") != "Synthetic coordinated backup":
            raise RuntimeError("Native backup lock is not reflected in the running web application.")
        run("exec", "-T", "mirklurk", "php", "/usr/local/lib/mirklurk/healthcheck.php")
        rejected(admin.upload("Locked.png", png()), "readonly")
    finally:
        run("exec", "-T", "mirklurk", "php", "-r", "unlink('/var/lib/mirklurk-backup/read-only');")
    # Restore the original newcomer policy for the rest of the integration suite.
    api({"action": "userrights", "user": "TestEditor", "remove": "confirmed",
         "reason": "End of upload fixture", "token": user_token}, post=True)
    run("up", "-d", "--force-recreate", "--wait", "mirklurk")
    with urllib.request.urlopen(second["imageinfo"]["url"], timeout=30) as response:
        if response.headers.get_content_type() != "image/png" or response.read() != png(pixel=b"\x22\x44\x66"):
            raise RuntimeError("Images were not preserved across container recreation.")
    print("Native uploads passed: eligibility, formats, limits, replacements, rate limit, storage protection and backup lock.",
          flush=True)
